#!/usr/bin/env node
/**
 * The single reader of version.json.
 *
 * Every build target, both CI jobs and both native builds derive their
 * identifiers here, so there is exactly one place where a version can be
 * wrong. See docs/cross-platform/release/VERSIONING.md for the contract.
 *
 * This performs no release action and has no public impact — it is a pure
 * derivation helper. The channel operations (preflight, web, ios-build, …)
 * are separate stubs implemented in Phase 9.
 *
 * Subcommands:
 *   env           print KEY=value lines for the five identifiers
 *   print         print version.json plus derived values as JSON
 *   bump <part>   rewrite app_version (major|minor|patch); leaves app_build
 *   build-bump    increment app_build, then apply-native
 *   apply-native  regenerate the iOS xcconfig and Android properties
 *   check         exit non-zero if anything disagrees with version.json
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const VERSION_FILE = resolve(ROOT, 'version.json');

// Native project paths. These do not exist until Phase 5 scaffolds the
// Capacitor shells, so every native operation tolerates their absence rather
// than failing — `check` must pass on a repo that has no native projects yet.
const IOS_XCCONFIG = resolve(ROOT, 'apps/web/ios/App/Version.xcconfig');
const ANDROID_PROPS = resolve(ROOT, 'apps/web/android/version.properties');

function readVersion() {
  if (!existsSync(VERSION_FILE)) {
    fail(`version.json not found at ${VERSION_FILE}`);
  }
  const raw = JSON.parse(readFileSync(VERSION_FILE, 'utf8'));

  if (typeof raw.app_version !== 'string' || !/^\d+\.\d+\.\d+$/.test(raw.app_version)) {
    fail(`app_version must be MAJOR.MINOR.PATCH, got ${JSON.stringify(raw.app_version)}`);
  }
  if (!Number.isInteger(raw.app_build) || raw.app_build < 1) {
    fail(`app_build must be a positive integer, got ${JSON.stringify(raw.app_build)}`);
  }
  return raw;
}

function writeVersion(v) {
  writeFileSync(VERSION_FILE, `${JSON.stringify(v, null, 2)}\n`);
}

function fail(message) {
  console.error(`version.mjs: ${message}`);
  process.exit(1);
}

/**
 * Short SHA. Prefers GITHUB_SHA so CI reports the commit under test rather
 * than whatever the checkout happens to have at HEAD.
 */
function shortSha() {
  const fromEnv = process.env.GITHUB_SHA;
  if (fromEnv) return fromEnv.trim().slice(0, 7);
  try {
    return execSync('git rev-parse HEAD', { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })
      .trim()
      .slice(0, 7);
  } catch {
    // A tarball export with no git history still needs to build.
    return 'nogit';
  }
}

function derive(v) {
  const sha = shortSha();
  const platform = process.env.CLIENT_PLATFORM ?? 'web';
  const environment = process.env.APP_ENVIRONMENT ?? 'production';

  if (!['web', 'ios', 'android'].includes(platform)) {
    fail(`CLIENT_PLATFORM must be web|ios|android, got ${platform}`);
  }
  if (!['production', 'staging', 'development'].includes(environment)) {
    fail(`APP_ENVIRONMENT must be production|staging|development, got ${environment}`);
  }

  // The one platform-shaped difference, and it is deliberate. Web is
  // continuously deployed on every push to main, so consuming a build integer
  // per deploy would mean a bot commit per deploy — which would retrigger CI.
  // The SHA *is* web's unique artifact id, so the field stays present and
  // uniquely identifying on all three platforms while only native uses the
  // counter. Consumers stay branch-free.
  const appBuild = platform === 'web' ? sha : String(v.app_build);

  return {
    NEXT_PUBLIC_APP_VERSION: v.app_version,
    NEXT_PUBLIC_APP_BUILD: appBuild,
    NEXT_PUBLIC_CLIENT_PLATFORM: platform,
    NEXT_PUBLIC_RELEASE_SHA: sha,
    NEXT_PUBLIC_ENVIRONMENT: environment,
  };
}

// ---------------------------------------------------------------------------
// Native artifact generation
// ---------------------------------------------------------------------------

function iosXcconfig(v) {
  return [
    '// Generated by scripts/release/version.mjs — do not edit.',
    '// Regenerate with: node scripts/release/version.mjs apply-native',
    `MARKETING_VERSION = ${v.app_version}`,
    `CURRENT_PROJECT_VERSION = ${v.app_build}`,
    '',
  ].join('\n');
}

function androidProperties(v) {
  return [
    '# Generated by scripts/release/version.mjs — do not edit.',
    '# Regenerate with: node scripts/release/version.mjs apply-native',
    `versionName=${v.app_version}`,
    `versionCode=${v.app_build}`,
    '',
  ].join('\n');
}

function applyNative(v, { quiet = false } = {}) {
  const written = [];

  for (const [path, contents, label] of [
    [IOS_XCCONFIG, iosXcconfig(v), 'ios'],
    [ANDROID_PROPS, androidProperties(v), 'android'],
  ]) {
    const dir = dirname(path);
    if (!existsSync(dir)) {
      // Native projects arrive in Phase 5. Skipping is correct, not an error.
      if (!quiet) console.log(`skipped ${label}: ${dir} does not exist yet`);
      continue;
    }
    writeFileSync(path, contents);
    written.push(path);
    if (!quiet) console.log(`wrote ${path}`);
  }

  return written;
}

// ---------------------------------------------------------------------------
// check
// ---------------------------------------------------------------------------

function check(v) {
  const problems = [];

  // Generated native files must match version.json.
  for (const [path, expected, label] of [
    [IOS_XCCONFIG, iosXcconfig(v), 'Version.xcconfig'],
    [ANDROID_PROPS, androidProperties(v), 'version.properties'],
  ]) {
    if (!existsSync(path)) continue; // not scaffolded yet
    const actual = readFileSync(path, 'utf8');
    if (actual !== expected) {
      problems.push(
        `${label} disagrees with version.json — run: node scripts/release/version.mjs apply-native`,
      );
    }
  }

  // A release tag visible from HEAD must not claim a different version. Tags
  // are only meaningful once Phase 9 starts cutting them; absence is fine.
  try {
    const described = execSync('git describe --tags --abbrev=0 --match "v*"', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    const tagged = described.replace(/^v/, '').split('+')[0];
    if (tagged && tagged !== v.app_version) {
      problems.push(
        `nearest release tag ${described} disagrees with version.json app_version ${v.app_version}`,
      );
    }
  } catch {
    // No tags yet — expected until Phase 9.
  }

  if (problems.length > 0) {
    for (const p of problems) console.error(`version.mjs: ${p}`);
    process.exit(1);
  }

  console.log(`ok — app_version ${v.app_version}, app_build ${v.app_build}`);
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

const command = process.argv[2];
const version = readVersion();

switch (command) {
  case 'env': {
    for (const [k, val] of Object.entries(derive(version))) {
      console.log(`${k}=${val}`);
    }
    break;
  }

  case 'print': {
    console.log(JSON.stringify({ ...version, derived: derive(version) }, null, 2));
    break;
  }

  case 'bump': {
    const part = process.argv[3];
    if (!['major', 'minor', 'patch'].includes(part)) {
      fail('usage: version.mjs bump major|minor|patch');
    }
    const [major, minor, patch] = version.app_version.split('.').map(Number);
    const next =
      part === 'major'
        ? `${major + 1}.0.0`
        : part === 'minor'
          ? `${major}.${minor + 1}.0`
          : `${major}.${minor}.${patch + 1}`;
    // Deliberately does not touch app_build: the native artifact counter moves
    // only when a native artifact is uploaded, not when the product version does.
    writeVersion({ ...version, app_version: next });
    console.log(`app_version ${version.app_version} -> ${next}`);
    applyNative({ ...version, app_version: next });
    break;
  }

  case 'build-bump': {
    const next = { ...version, app_build: version.app_build + 1 };
    writeVersion(next);
    console.log(`app_build ${version.app_build} -> ${next.app_build}`);
    applyNative(next);
    break;
  }

  case 'apply-native': {
    const written = applyNative(version);
    if (written.length === 0) {
      console.log('no native projects present — nothing to apply (expected before Phase 5)');
    }
    break;
  }

  case 'check': {
    check(version);
    break;
  }

  default:
    console.error(
      'usage: version.mjs env|print|bump <part>|build-bump|apply-native|check',
    );
    process.exit(1);
}
