INSERT INTO transfers.journalists (name, x_handle, primary_league, primary_clubs, country, language, source_type) VALUES
  ('Fabrizio Romano', '@FabrizioRomano', 'Multi (PL/Serie A/La Liga)', 'Multi-club', 'Italy', 'English/Italian', 'Global Reporter / Transfers'),
  ('David Ornstein', '@David_Ornstein', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Athletic'),
  ('Matteo Moretto', '@MatteMoretto', 'Multi (La Liga/PL/Serie A)', 'Multi-club', 'Italy/Spain', 'Spanish/Italian', 'Global Reporter / Transfers'),
  ('Rudy Galetti', '@RudyGaletti', 'Multi (Serie A/PL)', 'Multi-club', 'Italy', 'Italian/English', 'Global Reporter / Transfers'),
  ('Sam Lee', '@SamLee', 'Premier League', 'Manchester City', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('James Pearce', '@JamesPearceLFC', 'Premier League', 'Liverpool', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Laurie Whitwell', '@lauriewhitwell', 'Premier League', 'Manchester United', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('James McNicholas', '@gunnerblog', 'Premier League', 'Arsenal', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Phil Hay', '@PhilHay_', 'Premier League', 'Leeds United', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Dominic Fifield', '@domfifield', 'Premier League', 'Chelsea', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Liam Twomey', '@liam_twomey', 'Premier League', 'Chelsea', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Chris Waugh', '@ChrisDHWaugh', 'Premier League', 'Newcastle United', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Patrick Boyland', '@paddyboyland', 'Premier League', 'Everton', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Caoimhe O''Neill', '@CaoimheSport', 'Premier League', 'Everton/Liverpool', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Andy Naylor', '@andy_naylor_', 'Premier League', 'Brighton', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Jay Harris', '@jaydmharris', 'Premier League', 'Tottenham', 'United Kingdom', 'English', 'Club Beat Reporter / The Athletic'),
  ('Adam Crafton', '@AdamCrafton_', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Athletic'),
  ('Daniel Taylor', '@DTathletic', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Athletic'),
  ('Oliver Kay', '@OliverKay', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Athletic'),
  ('Henry Winter', '@henrywinter', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Times'),
  ('Paul Joyce', '@_pauljoyce', 'Premier League', 'Liverpool/Merseyside', 'United Kingdom', 'English', 'Club Beat Reporter / The Times'),
  ('Martyn Ziegler', '@martynziegler', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Times'),
  ('Tom Roddy', '@TomRoddy_', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Times'),
  ('Jonathan Northcroft', '@JNorthcroft', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Sunday Times'),
  ('Paul Hirst', '@hirstclass', 'Premier League', 'Manchester United', 'United Kingdom', 'English', 'Club Beat Reporter / The Times'),
  ('Matt Law', '@Matt_Law_DT', 'Premier League', 'Chelsea', 'United Kingdom', 'English', 'Club Beat Reporter / The Telegraph'),
  ('Jason Burt', '@JBurtTelegraph', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Telegraph'),
  ('Sam Wallace', '@SamWallaceTel', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Telegraph'),
  ('Chris Bascombe', '@ChrisBascombe', 'Premier League', 'Liverpool', 'United Kingdom', 'English', 'Club Beat Reporter / The Telegraph'),
  ('Mike McGrath', '@Mike_McGrath_', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Telegraph'),
  ('John Cross', '@johncrossmirror', 'Premier League', 'Arsenal', 'United Kingdom', 'English', 'Club Beat Reporter / Daily Mirror'),
  ('David McDonnell', '@MirrorMcDonnell', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Daily Mirror'),
  ('Mike Keegan', '@Mike_Keegan_DM', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Daily Mail'),
  ('Ian Ladyman', '@Ian_Ladyman_DM', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Daily Mail'),
  ('Chris Wheeler', '@ChrisWheelerDM', 'Premier League', 'Manchester United', 'United Kingdom', 'English', 'Club Beat Reporter / Daily Mail'),
  ('Matt Hughes', '@Matt_HughesDM', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Daily Mail'),
  ('Miguel Delaney', '@MiguelDelaney', 'Premier League', 'Multi-club', 'Ireland', 'English', 'League Reporter / The Independent'),
  ('Jacob Steinberg', '@JacobSteinberg', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Guardian'),
  ('David Hytner', '@DHytner', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Guardian'),
  ('Jonathan Liew', '@jonathanliew', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Columnist / The Guardian'),
  ('Barney Ronay', '@barneyronay', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Columnist / The Guardian'),
  ('Jamie Jackson', '@JamieJackson___', 'Premier League', 'Manchester United/City', 'United Kingdom', 'English', 'Club Beat Reporter / The Guardian'),
  ('Andy Hunter', '@AHunterGuardian', 'Premier League', 'Liverpool/Everton', 'United Kingdom', 'English', 'Club Beat Reporter / The Guardian'),
  ('Phil McNulty', '@philmcnulty', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Chief Reporter / BBC Sport'),
  ('Simon Stone', '@sistoney67', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / BBC Sport'),
  ('Sami Mokbel', '@SamiMokbel81_DM', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Daily Mail/BBC'),
  ('Rob Dawson', '@RobDawsonESPN', 'Premier League', 'Manchester United', 'United Kingdom', 'English', 'Club Beat Reporter / ESPN'),
  ('Mark Ogden', '@MarkOgden_', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / ESPN'),
  ('Kaveh Solhekol', '@SkyKaveh', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Transfer Reporter / Sky Sports'),
  ('Melissa Reddy', '@MelissaReddy_', 'Premier League', 'Liverpool/Multi-club', 'United Kingdom', 'English', 'League Reporter / Sky Sports'),
  ('Charles Watts', '@charles_watts', 'Premier League', 'Arsenal', 'United Kingdom', 'English', 'Independent Club Reporter'),
  ('Dean Jones', '@DeanJonesSoccer', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Transfer Reporter / GiveMeSport'),
  ('Ben Jacobs', '@JacobsBen', 'Multi (PL/Saudi)', 'Multi-club', 'United Kingdom', 'English', 'Transfer Reporter / GiveMeSport'),
  ('Tom Allnutt', '@TomAllnutt', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / AFP'),
  ('Samuel Luckhurst', '@samuelluckhurst', 'Premier League', 'Manchester United', 'United Kingdom', 'English', 'Club Beat Reporter / Manchester Evening News'),
  ('Stuart Mathieson', '@StuartMathieson', 'Premier League', 'Manchester United', 'United Kingdom', 'English', 'Club Beat Reporter / Manchester Evening News'),
  ('Stuart Brennan', '@StuBrennanMEN', 'Premier League', 'Manchester City', 'United Kingdom', 'English', 'Club Beat Reporter / Manchester Evening News'),
  ('Joe Bray', '@JoeBrayMEN', 'Premier League', 'Manchester City', 'United Kingdom', 'English', 'Club Beat Reporter / Manchester Evening News'),
  ('Ian Doyle', '@ianjdoyle', 'Premier League', 'Liverpool', 'United Kingdom', 'English', 'Club Beat Reporter / Liverpool Echo'),
  ('Paul Gorst', '@ptgorst', 'Premier League', 'Liverpool', 'United Kingdom', 'English', 'Club Beat Reporter / Liverpool Echo'),
  ('Connor Dunn', '@ConnorDunnLE', 'Premier League', 'Everton', 'United Kingdom', 'English', 'Club Beat Reporter / Liverpool Echo'),
  ('Ciaran Kelly', '@Ciaran_Kelly', 'Premier League', 'Newcastle United', 'United Kingdom', 'English', 'Club Beat Reporter / Newcastle Chronicle'),
  ('Lee Ryder', '@lee_ryder', 'Premier League', 'Newcastle United', 'United Kingdom', 'English', 'Club Beat Reporter / Newcastle Chronicle'),
  ('Beren Cross', '@BerenCross', 'Premier League', 'Leeds United', 'United Kingdom', 'English', 'Club Beat Reporter / Yorkshire Evening Post'),
  ('Alan Smith', '@AlanSmithJourno', 'Premier League', 'Aston Villa', 'United Kingdom', 'English', 'Club Beat Reporter / Birmingham Mail'),
  ('Ashley Preece', '@AshPreeceBMail', 'Premier League', 'Aston Villa', 'United Kingdom', 'English', 'Club Beat Reporter / Birmingham Mail'),
  ('Alex Crook', '@AlexCrookTalkSPORT', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Transfer Reporter / talkSPORT'),
  ('Sid Lowe', '@sidlowe', 'La Liga', 'Multi-club', 'United Kingdom', 'English/Spanish', 'Global Reporter / The Guardian'),
  ('Guillem Balagué', '@GuillemBalague', 'La Liga', 'Multi-club', 'Spain', 'English/Spanish', 'Global Reporter / BBC/Various'),
  ('Graham Hunter', '@BumperGraham', 'La Liga', 'Barcelona/Multi', 'United Kingdom', 'English/Spanish', 'Global Reporter / Independent'),
  ('Bruno Alemany', '@BrunoAlemany', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'League Reporter / ESPN/Cope'),
  ('Adriana Garcia', '@AdrianaGarcia', 'La Liga', 'Real Madrid', 'Spain', 'Spanish/English', 'Club Beat Reporter / ESPN'),
  ('José Félix Díaz', '@JoseFelix_Diaz', 'La Liga', 'Real Madrid', 'Spain', 'Spanish', 'Club Beat Reporter / Marca'),
  ('Tomás Roncero', '@TomasRoncero', 'La Liga', 'Real Madrid', 'Spain', 'Spanish', 'Columnist / AS'),
  ('Antón Meana', '@antonmeana', 'La Liga', 'Real Madrid', 'Spain', 'Spanish', 'Club Beat Reporter / Cadena SER'),
  ('Alfredo Martínez', '@Alfremartinezz', 'La Liga', 'Barcelona', 'Spain', 'Spanish', 'Club Beat Reporter / Onda Cero'),
  ('Edu Pidal', '@EduPidal', 'La Liga', 'Real Madrid', 'Spain', 'Spanish', 'Club Beat Reporter / Cadena COPE'),
  ('Helena Condis', '@HelenaCondis', 'La Liga', 'Barcelona', 'Spain', 'Spanish', 'Club Beat Reporter / Cadena COPE'),
  ('Ruben Martin', '@rmartin1989', 'La Liga', 'Real Madrid', 'Spain', 'Spanish', 'Club Beat Reporter / Marca'),
  ('Fernando Polo', '@ferpolo', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish', 'Club Beat Reporter / Mundo Deportivo'),
  ('Lluís Mascaró', '@lluismascaro', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish/Catalan', 'Club Beat Reporter / Sport'),
  ('Toni Juanmarti', '@TJuanmarti', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish/Catalan', 'Club Beat Reporter / Sport'),
  ('Marc Guillén', '@MarcGuillen10', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish/Catalan', 'Club Beat Reporter / Sport'),
  ('Gerard Romero', '@gerardromero', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish/Catalan', 'Independent / Jijantes FC'),
  ('Ramon Besa', '@ramon_besa', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish/Catalan', 'Columnist / El País'),
  ('Sique Rodríguez', '@SiqueRodriguez', 'La Liga', 'FC Barcelona', 'Spain', 'Spanish/Catalan', 'Club Beat Reporter / Cadena SER'),
  ('José Sánchez', '@JoseSanchez_M', 'La Liga', 'Atlético Madrid', 'Spain', 'Spanish', 'Club Beat Reporter / Marca'),
  ('Miguel Quintana', '@miguelquintana_', 'La Liga', 'Atlético Madrid', 'Spain', 'Spanish', 'Club Beat Reporter / Marca'),
  ('Josep Pedrerol', '@jpedrerol', 'La Liga', 'Real Madrid', 'Spain', 'Spanish', 'Host / El Chiringuito'),
  ('Manu Carreño', '@ManuCarreno', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Host / Cadena SER'),
  ('Jesús Gallego', '@jgallegofc', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Host / Cadena COPE'),
  ('Roberto Palomar', '@RobertoPalomar', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Columnist / Marca'),
  ('Santi Giménez', '@santigimenez', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Columnist / AS'),
  ('Alfredo Relaño', '@AlfredoRelano', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Columnist / AS'),
  ('Marca', '@marca', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Major Outlet'),
  ('Diario AS', '@diarioas', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Major Outlet'),
  ('Mundo Deportivo', '@mundodeportivo', 'La Liga', 'FC Barcelona-focused', 'Spain', 'Spanish', 'Major Outlet'),
  ('Diario Sport', '@sport', 'La Liga', 'FC Barcelona-focused', 'Spain', 'Spanish/Catalan', 'Major Outlet'),
  ('Relevo', '@relevo', 'La Liga', 'Multi-club', 'Spain', 'Spanish', 'Major Outlet'),
  ('Raphael Honigstein', '@honigstein', 'Bundesliga', 'Multi-club', 'Germany/UK', 'English/German', 'Global Reporter / The Athletic'),
  ('Seb Stafford-Bloor', '@SebSB', 'Bundesliga', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / The Athletic'),
  ('Constantin Eckner', '@cre80s', 'Bundesliga', 'Multi-club', 'Germany', 'English/German', 'Tactics Writer / Various'),
  ('Manuel Veth', '@ManuelVeth', 'Bundesliga', 'Multi-club', 'Germany', 'English/German', 'League Reporter / Forbes'),
  ('Archie Rhind-Tutt', '@archiert1', 'Bundesliga', 'Multi-club', 'United Kingdom', 'English', 'Commentator / ESPN/Sky'),
  ('Kevin Hatchard', '@kevinhatchard', 'Bundesliga', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Various'),
  ('Florian Plettenberg', '@Plettigoal', 'Bundesliga', 'Bayern Munich/DFB', 'Germany', 'German/English', 'Transfer Reporter / Sky Germany'),
  ('Christian Falk', '@cfbayern', 'Bundesliga', 'Bayern Munich', 'Germany', 'German/English', 'Club Beat Reporter / Bild'),
  ('Tobi Altschäffl', '@TAltschaeffl', 'Bundesliga', 'Bayern Munich', 'Germany', 'German', 'Club Beat Reporter / Bild'),
  ('Patrick Strasser', '@stra_patrick', 'Bundesliga', 'Bayern Munich', 'Germany', 'German', 'Club Beat Reporter / AZ Munich'),
  ('Kerry Hau', '@KerryHau', 'Bundesliga', 'Bayern Munich', 'Germany', 'German', 'Club Beat Reporter / Sport1'),
  ('Marc Behrenbeck', '@MarcBehrenbeck', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'League Reporter / Sky Germany'),
  ('Patrick Berger', '@PBergerBR', 'Bundesliga', 'Bayer Leverkusen/Multi', 'Germany', 'German', 'League Reporter / Sky Germany'),
  ('Dirk Krümpelmann', '@DKruempelmann', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'League Reporter / Bild'),
  ('Lars Pollmann', '@_LarsPollmann', 'Bundesliga', 'Borussia Dortmund', 'Germany', 'German', 'Club Beat Reporter / Bild'),
  ('Sascha Fligge', '@saschafligge', 'Bundesliga', 'Borussia Dortmund', 'Germany', 'German', 'Club Beat Reporter / Ruhr Nachrichten'),
  ('Tobias Escher', '@TobiasEscher', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'Tactics Analyst / Spielverlagerung'),
  ('Lars Wallrodt', '@larswallrodt', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'League Reporter / Welt'),
  ('Get German Football News', '@GGFN_', 'Bundesliga', 'Multi-club', 'Germany', 'English', 'Major Outlet (English)'),
  ('Bundesliga (official)', '@Bundesliga_EN', 'Bundesliga', 'Multi-club', 'Germany', 'English', 'Official League Account'),
  ('Bild Sport', '@BILD_Sport', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'Major Outlet'),
  ('Kicker', '@kicker_BL', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'Major Outlet'),
  ('Sky Sport DE', '@SkySportDE', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'Major Outlet'),
  ('Sport1', '@SPORT1', 'Bundesliga', 'Multi-club', 'Germany', 'German', 'Major Outlet'),
  ('Gianluca Di Marzio', '@DiMarzio', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Transfer Reporter / Sky Italia'),
  ('Nicolò Schira', '@NicoSchira', 'Serie A', 'Multi-club', 'Italy', 'Italian/English', 'Transfer Reporter / Various'),
  ('Alfredo Pedullà', '@AlfredoPedulla', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Transfer Reporter / Various'),
  ('Daniele Longo', '@longoale', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Transfer Reporter / Calciomercato'),
  ('Fabrizio Biasin', '@FBiasin', 'Serie A', 'Inter Milan', 'Italy', 'Italian', 'Club Beat Reporter / Libero'),
  ('Pasquale Salvione', '@SkySalvione', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'League Reporter / Sky Italia'),
  ('Romeo Agresti', '@romeoagresti', 'Serie A', 'Juventus', 'Italy', 'Italian/English', 'Club Beat Reporter / Goal Italy'),
  ('Matteo Pifferi', '@MatteoPifferi', 'Serie A', 'Juventus', 'Italy', 'Italian', 'Club Beat Reporter / Various'),
  ('Vincenzo D''Angelo', '@vinncasso', 'Serie A', 'Juventus', 'Italy', 'Italian', 'Club Beat Reporter / Gazzetta'),
  ('Tancredi Palmeri', '@tancredipalmeri', 'Serie A', 'Multi-club', 'Italy', 'Italian/English', 'League Reporter / BeIN Sports'),
  ('Carlo Garganese', '@cgarganese', 'Serie A', 'Multi-club', 'Italy/UK', 'English/Italian', 'League Reporter / Various'),
  ('Marco Conterio', '@marcoconterio', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Transfer Reporter / TMW'),
  ('Filippo Bonsignore', '@bonsignore_f', 'Serie A', 'AC Milan', 'Italy', 'Italian', 'Club Beat Reporter / Gazzetta'),
  ('Alessandro Schiavone', '@AleSchiavone', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'League Reporter / Various'),
  ('James Horncastle', '@JamesHorncastle', 'Serie A', 'Multi-club', 'United Kingdom', 'English', 'Global Reporter / The Athletic'),
  ('Adam Digby', '@Adz77', 'Serie A', 'Juventus/Multi', 'United Kingdom', 'English', 'Global Reporter / Various'),
  ('Paolo Bandini', '@Paolo_Bandini', 'Serie A', 'Multi-club', 'United Kingdom', 'English/Italian', 'Global Reporter / The Guardian'),
  ('Mina Rzouki', '@Minarzouki', 'Serie A', 'Juventus/Multi', 'United Kingdom', 'English', 'League Pundit / Various'),
  ('Susy Campanale', '@SusyFI', 'Serie A', 'Multi-club', 'Italy/UK', 'English/Italian', 'League Reporter / Football Italia'),
  ('Gabriele Marcotti', '@Marcotti', 'Multi (Serie A/PL)', 'Multi-club', 'Italy/UK', 'English/Italian', 'Global Columnist / ESPN/The Times'),
  ('La Gazzetta dello Sport', '@Gazzetta_it', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Major Outlet'),
  ('Corriere dello Sport', '@CorSport', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Major Outlet'),
  ('Tuttosport', '@tuttosport', 'Serie A', 'Juventus/Torino-focused', 'Italy', 'Italian', 'Major Outlet'),
  ('Sky Sport Italia', '@SkySport', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Major Outlet'),
  ('Calciomercato.com', '@cmdotcom', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Major Outlet'),
  ('TuttoMercatoWeb', '@TuttoMercatoWeb', 'Serie A', 'Multi-club', 'Italy', 'Italian', 'Major Outlet'),
  ('Football Italia', '@footballitalia', 'Serie A', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet (English)'),
  ('Mohamed Bouhafsi', '@mohamedbouhafsi', 'Ligue 1', 'Multi-club', 'France', 'French', 'Transfer Reporter / RMC Sport'),
  ('Loïc Tanzi', '@LoicTanzi', 'Ligue 1', 'Multi-club', 'France', 'French', 'Transfer Reporter / L''Equipe'),
  ('Hugo Guillemet', '@HugoGuillemet', 'Ligue 1', 'Olympique Lyonnais', 'France', 'French', 'Club Beat Reporter / L''Equipe'),
  ('Daniel Riolo', '@DanielRiolo', 'Ligue 1', 'Multi-club', 'France', 'French', 'Columnist / RMC Sport'),
  ('Jérôme Rothen', '@RothenJerome', 'Ligue 1', 'PSG/Multi', 'France', 'French', 'Pundit / RMC Sport'),
  ('Vincent Duluc', '@Duluc_Vincent', 'Ligue 1', 'Olympique Lyonnais/Multi', 'France', 'French', 'Columnist / L''Equipe'),
  ('Bilel Ghazi', '@Bilel_Ghazi', 'Ligue 1', 'Multi-club', 'France', 'French', 'League Reporter / L''Equipe'),
  ('Sebastien Tarrago', '@SebTarrago', 'Ligue 1', 'Multi-club', 'France', 'French', 'League Reporter / L''Equipe'),
  ('Hadrien Grenier', '@HadrienGrenier_', 'Ligue 1', 'Paris Saint-Germain', 'France', 'French', 'PSG Reporter / Independent'),
  ('Saber Desfarges', '@saberdesfarges', 'Ligue 1', 'Multi-club', 'France', 'French', 'Commentator / Canal+'),
  ('Nabil Djellit', '@Nabil_djellit', 'Ligue 1', 'Multi-club', 'France', 'French', 'Columnist / France Football'),
  ('Romain Molina', '@romainmolina', 'Ligue 1', 'Multi-club', 'France', 'English/French', 'Investigative Reporter / Independent'),
  ('Julien Laurens', '@LaurensJulien', 'Ligue 1', 'Multi-club', 'France', 'English/French', 'Global Reporter / ESPN/BBC'),
  ('Jonathan Johnson', '@Jon_LeGossip', 'Ligue 1', 'PSG/Multi', 'United Kingdom', 'English', 'Global Reporter / CBS'),
  ('Andy Brassell', '@andybrassell', 'Ligue 1', 'Multi-club', 'United Kingdom', 'English', 'Global Reporter / Various'),
  ('Adam White', '@FrenchFooty', 'Ligue 1', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Get French Football News'),
  ('Luke Entwistle', '@LukeEntwistle', 'Ligue 1', 'Multi-club', 'United Kingdom', 'English', 'League Reporter / Get French Football News'),
  ('Damien Degorre', '@DamienDegorre', 'Ligue 1', 'PSG', 'France', 'French', 'Club Beat Reporter / L''Equipe'),
  ('Mathieu Coureau', '@mathieucoureau', 'Ligue 1', 'Olympique de Marseille', 'France', 'French', 'Club Beat Reporter / La Provence'),
  ('Florent Germain', '@F_Germain', 'Ligue 1', 'Olympique de Marseille', 'France', 'French', 'Club Beat Reporter / RMC Sport'),
  ('Gregory Schneider', '@GSchneider_OL', 'Ligue 1', 'Olympique Lyonnais', 'France', 'French', 'Club Beat Reporter / Le Progrès'),
  ('Razik Brikh', '@RazikBrikh', 'Ligue 1', 'Multi-club', 'France', 'French', 'League Reporter / Foot Mercato'),
  ('Santi Aouna', '@Santi_J7', 'Ligue 1', 'Multi-club', 'France', 'French', 'Transfer Reporter / Foot Mercato'),
  ('L''Equipe', '@lequipe', 'Ligue 1', 'Multi-club', 'France', 'French', 'Major Outlet'),
  ('RMC Sport', '@RMCsport', 'Ligue 1', 'Multi-club', 'France', 'French', 'Major Outlet'),
  ('Le Parisien', '@le_Parisien', 'Ligue 1', 'PSG/Paris-focused', 'France', 'French', 'Major Outlet'),
  ('Foot Mercato', '@footmercato', 'Ligue 1', 'Multi-club', 'France', 'French', 'Major Outlet'),
  ('So Foot', '@sofoot', 'Ligue 1', 'Multi-club', 'France', 'French', 'Major Outlet'),
  ('Le10Sport', '@le10sport', 'Ligue 1', 'Multi-club', 'France', 'French', 'Major Outlet'),
  ('France Football', '@francefootball', 'Ligue 1', 'Multi-club', 'France', 'French', 'Major Outlet'),
  ('Get French Football News', '@GFFN', 'Ligue 1', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet (English)'),
  ('The Athletic UK', '@TheAthleticFC', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('Sky Sports News', '@SkySportsNews', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('BBC Sport', '@BBCSport', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('Guardian Football', '@guardian_sport', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('Telegraph Football', '@TeleFootball', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('The Times Sport', '@TimesSport', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('Daily Mail Football', '@MailSport', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('Mirror Football', '@MirrorFootball', 'Premier League', 'Multi-club', 'United Kingdom', 'English', 'Major Outlet'),
  ('ESPN FC', '@ESPNFC', 'Multi (PL/Global)', 'Multi-club', 'United States', 'English', 'Major Outlet'),
  ('Goal.com', '@goal', 'Multi (Global)', 'Multi-club', 'Multi-country', 'Multiple', 'Major Outlet')
ON CONFLICT (x_handle) DO NOTHING;;