INSERT INTO transfers.clubs (name, short_name, aliases, league_id, country) VALUES
  ('Arsenal', 'Arsenal', ARRAY['AFC', 'Gunners', 'The Arsenal']::text[], 1, 'England'),
  ('Aston Villa', 'Villa', ARRAY['AVFC', 'The Villans']::text[], 1, 'England'),
  ('AFC Bournemouth', 'Bournemouth', ARRAY['The Cherries', 'AFCB']::text[], 1, 'England'),
  ('Brentford', 'Brentford', ARRAY['BFC', 'The Bees']::text[], 1, 'England'),
  ('Brighton & Hove Albion', 'Brighton', ARRAY['Brighton and Hove Albion', 'BHAFC', 'The Seagulls']::text[], 1, 'England'),
  ('Burnley', 'Burnley', ARRAY['BFC', 'The Clarets']::text[], 1, 'England'),
  ('Chelsea', 'Chelsea', ARRAY['CFC', 'The Blues', 'Chelsea FC']::text[], 1, 'England'),
  ('Crystal Palace', 'Palace', ARRAY['CPFC', 'The Eagles']::text[], 1, 'England'),
  ('Everton', 'Everton', ARRAY['EFC', 'The Toffees']::text[], 1, 'England'),
  ('Fulham', 'Fulham', ARRAY['FFC', 'The Cottagers']::text[], 1, 'England'),
  ('Leeds United', 'Leeds', ARRAY['LUFC', 'The Whites']::text[], 1, 'England'),
  ('Liverpool', 'Liverpool', ARRAY['LFC', 'The Reds', 'Liverpool FC']::text[], 1, 'England'),
  ('Manchester City', 'Man City', ARRAY['Man C', 'MCFC', 'City', 'Cityzens', 'Manchester C', 'Manchester City FC']::text[], 1, 'England'),
  ('Manchester United', 'Man United', ARRAY['Man Utd', 'MUFC', 'United', 'Red Devils', 'Manchester U', 'Man U', 'Manchester United FC']::text[], 1, 'England'),
  ('Newcastle United', 'Newcastle', ARRAY['NUFC', 'The Magpies', 'Toon', 'The Toon']::text[], 1, 'England'),
  ('Nottingham Forest', 'Forest', ARRAY['NFFC', 'Nott''m Forest', 'Notts Forest']::text[], 1, 'England'),
  ('Sunderland', 'Sunderland', ARRAY['SAFC', 'The Black Cats']::text[], 1, 'England'),
  ('Tottenham Hotspur', 'Tottenham', ARRAY['Spurs', 'THFC', 'Tottenham FC']::text[], 1, 'England'),
  ('West Ham United', 'West Ham', ARRAY['WHUFC', 'The Hammers', 'Irons']::text[], 1, 'England'),
  ('Wolverhampton Wanderers', 'Wolves', ARRAY['WWFC', 'Wolverhampton']::text[], 1, 'England'),
  ('Real Madrid', 'Real Madrid', ARRAY['Madrid', 'Los Blancos', 'Real Madrid CF', 'RMA', 'Real']::text[], 2, 'Spain'),
  ('FC Barcelona', 'Barcelona', ARRAY['Barça', 'Barca', 'FCB', 'Barcelona FC', 'Blaugrana', 'Culés']::text[], 2, 'Spain'),
  ('Atlético Madrid', 'Atlético', ARRAY['Atletico Madrid', 'Atletico', 'Atleti', 'ATM', 'Club Atlético de Madrid', 'Atlético de Madrid', 'Rojiblancos']::text[], 2, 'Spain'),
  ('Athletic Bilbao', 'Athletic', ARRAY['Athletic Club', 'Athletic Club de Bilbao', 'Bilbao', 'Los Leones']::text[], 2, 'Spain'),
  ('Real Sociedad', 'Real Sociedad', ARRAY['La Real', 'Sociedad', 'Real Sociedad de Fútbol', 'Txuri-urdin']::text[], 2, 'Spain'),
  ('Real Betis', 'Betis', ARRAY['Real Betis Balompié', 'Betis Balompié', 'Béticos']::text[], 2, 'Spain'),
  ('Villarreal', 'Villarreal', ARRAY['Villarreal CF', 'The Yellow Submarine', 'Submarino Amarillo']::text[], 2, 'Spain'),
  ('Sevilla', 'Sevilla', ARRAY['Sevilla FC', 'Los Nervionenses']::text[], 2, 'Spain'),
  ('Valencia', 'Valencia', ARRAY['Valencia CF', 'Los Che']::text[], 2, 'Spain'),
  ('Celta Vigo', 'Celta', ARRAY['Celta de Vigo', 'RC Celta', 'RC Celta de Vigo', 'Celestes']::text[], 2, 'Spain'),
  ('RCD Mallorca', 'Mallorca', ARRAY['Real Mallorca', 'Real Club Deportivo Mallorca', 'Los Bermellones']::text[], 2, 'Spain'),
  ('CA Osasuna', 'Osasuna', ARRAY['Club Atlético Osasuna', 'Los Rojillos']::text[], 2, 'Spain'),
  ('Getafe', 'Getafe', ARRAY['Getafe CF', 'Los Azulones']::text[], 2, 'Spain'),
  ('Rayo Vallecano', 'Rayo', ARRAY['Rayo Vallecano de Madrid', 'Los Franjirrojos']::text[], 2, 'Spain'),
  ('RCD Espanyol', 'Espanyol', ARRAY['Espanyol Barcelona', 'Real Club Deportivo Espanyol', 'Pericos']::text[], 2, 'Spain'),
  ('Deportivo Alavés', 'Alavés', ARRAY['Alaves', 'Deportivo Alaves', 'Babazorros']::text[], 2, 'Spain'),
  ('Girona', 'Girona', ARRAY['Girona FC']::text[], 2, 'Spain'),
  ('Real Oviedo', 'Oviedo', ARRAY['Real Oviedo SAD', 'Carbayones']::text[], 2, 'Spain'),
  ('Levante', 'Levante', ARRAY['Levante UD', 'Granotas']::text[], 2, 'Spain'),
  ('Elche', 'Elche', ARRAY['Elche CF', 'Franjiverdes']::text[], 2, 'Spain'),
  ('Bayern Munich', 'Bayern', ARRAY['FC Bayern', 'Bayern München', 'FC Bayern München', 'Bayern Munchen', 'FCB', 'Die Bayern', 'Rekordmeister']::text[], 3, 'Germany'),
  ('Borussia Dortmund', 'Dortmund', ARRAY['BVB', 'BV Borussia 09 Dortmund', 'Die Schwarzgelben']::text[], 3, 'Germany'),
  ('RB Leipzig', 'Leipzig', ARRAY['RasenBallsport Leipzig', 'Die Roten Bullen', 'Red Bulls']::text[], 3, 'Germany'),
  ('Bayer Leverkusen', 'Leverkusen', ARRAY['Bayer 04 Leverkusen', 'Bayer 04', 'Die Werkself']::text[], 3, 'Germany'),
  ('VfB Stuttgart', 'Stuttgart', ARRAY['VfB', 'Die Schwaben']::text[], 3, 'Germany'),
  ('Eintracht Frankfurt', 'Frankfurt', ARRAY['SGE', 'Die Adler']::text[], 3, 'Germany'),
  ('SC Freiburg', 'Freiburg', ARRAY['Sport-Club Freiburg', 'SCF', 'Breisgau-Brasilianer']::text[], 3, 'Germany'),
  ('VfL Wolfsburg', 'Wolfsburg', ARRAY['VfL', 'Die Wölfe']::text[], 3, 'Germany'),
  ('Borussia Mönchengladbach', 'Gladbach', ARRAY['Monchengladbach', 'Mönchengladbach', 'Borussia Monchengladbach', 'BMG', 'Die Fohlen']::text[], 3, 'Germany'),
  ('Werder Bremen', 'Bremen', ARRAY['SV Werder Bremen', 'Werder', 'Die Werderaner']::text[], 3, 'Germany'),
  ('1. FC Union Berlin', 'Union Berlin', ARRAY['Union', 'FC Union Berlin', 'Die Eisernen']::text[], 3, 'Germany'),
  ('FC Augsburg', 'Augsburg', ARRAY['FCA', 'Die Fuggerstädter']::text[], 3, 'Germany'),
  ('TSG 1899 Hoffenheim', 'Hoffenheim', ARRAY['TSG Hoffenheim', 'TSG', 'Die Kraichgauer']::text[], 3, 'Germany'),
  ('1. FSV Mainz 05', 'Mainz', ARRAY['FSV Mainz', 'Mainz 05', 'Die Nullfünfer']::text[], 3, 'Germany'),
  ('FC St. Pauli', 'St. Pauli', ARRAY['St Pauli', 'FC Sankt Pauli', 'Die Kiezkicker']::text[], 3, 'Germany'),
  ('1. FC Heidenheim', 'Heidenheim', ARRAY['FC Heidenheim', 'FCH']::text[], 3, 'Germany'),
  ('Hamburger SV', 'Hamburg', ARRAY['HSV', 'Hamburger Sport-Verein', 'Die Rothosen']::text[], 3, 'Germany'),
  ('1. FC Köln', 'Köln', ARRAY['FC Koln', 'Koln', '1. FC Koln', 'FC Köln', 'Cologne', 'Die Geißböcke']::text[], 3, 'Germany'),
  ('Juventus', 'Juventus', ARRAY['Juve', 'JUV', 'Juventus FC', 'Bianconeri', 'La Vecchia Signora']::text[], 4, 'Italy'),
  ('Inter Milan', 'Inter', ARRAY['Internazionale', 'FC Internazionale', 'FC Internazionale Milano', 'Nerazzurri', 'Inter Milano']::text[], 4, 'Italy'),
  ('AC Milan', 'Milan', ARRAY['Milan', 'Associazione Calcio Milan', 'Rossoneri', 'Diavolo']::text[], 4, 'Italy'),
  ('Napoli', 'Napoli', ARRAY['SSC Napoli', 'Società Sportiva Calcio Napoli', 'Partenopei', 'Azzurri']::text[], 4, 'Italy'),
  ('AS Roma', 'Roma', ARRAY['Associazione Sportiva Roma', 'Giallorossi', 'Lupi']::text[], 4, 'Italy'),
  ('Lazio', 'Lazio', ARRAY['SS Lazio', 'Società Sportiva Lazio', 'Biancocelesti', 'Aquile']::text[], 4, 'Italy'),
  ('Atalanta', 'Atalanta', ARRAY['Atalanta BC', 'Atalanta Bergamasca Calcio', 'La Dea', 'Nerazzurri di Bergamo']::text[], 4, 'Italy'),
  ('Fiorentina', 'Fiorentina', ARRAY['ACF Fiorentina', 'Viola', 'La Viola']::text[], 4, 'Italy'),
  ('Bologna', 'Bologna', ARRAY['Bologna FC', 'Bologna FC 1909', 'Rossoblù', 'Felsinei']::text[], 4, 'Italy'),
  ('Torino', 'Torino', ARRAY['Torino FC', 'Toro', 'Granata']::text[], 4, 'Italy'),
  ('Udinese', 'Udinese', ARRAY['Udinese Calcio', 'Bianconeri Friulani', 'Zebrette']::text[], 4, 'Italy'),
  ('Genoa', 'Genoa', ARRAY['Genoa CFC', 'Genoa Cricket and Football Club', 'Rossoblù', 'Grifone']::text[], 4, 'Italy'),
  ('Hellas Verona', 'Verona', ARRAY['Hellas', 'Hellas Verona FC', 'Gialloblù', 'Mastini']::text[], 4, 'Italy'),
  ('Lecce', 'Lecce', ARRAY['US Lecce', 'Unione Sportiva Lecce', 'Giallorossi']::text[], 4, 'Italy'),
  ('Como', 'Como', ARRAY['Como 1907', 'Lariani', 'Azzurri']::text[], 4, 'Italy'),
  ('Parma', 'Parma', ARRAY['Parma Calcio 1913', 'Parma FC', 'Crociati', 'Ducali']::text[], 4, 'Italy'),
  ('Cagliari', 'Cagliari', ARRAY['Cagliari Calcio', 'Rossoblù', 'Casteddu']::text[], 4, 'Italy'),
  ('Sassuolo', 'Sassuolo', ARRAY['US Sassuolo', 'US Sassuolo Calcio', 'Neroverdi']::text[], 4, 'Italy'),
  ('Pisa', 'Pisa', ARRAY['Pisa SC', 'Pisa Sporting Club', 'Nerazzurri']::text[], 4, 'Italy'),
  ('Cremonese', 'Cremonese', ARRAY['US Cremonese', 'Unione Sportiva Cremonese', 'Grigiorossi']::text[], 4, 'Italy'),
  ('Paris Saint-Germain', 'PSG', ARRAY['Paris SG', 'Paris', 'Les Parisiens', 'Paris Saint Germain', 'PSG FC']::text[], 5, 'France'),
  ('Olympique de Marseille', 'Marseille', ARRAY['OM', 'Olympique Marseille', 'Les Phocéens', 'Les Olympiens']::text[], 5, 'France'),
  ('AS Monaco', 'Monaco', ARRAY['Association Sportive de Monaco', 'ASM', 'Les Monégasques', 'Rouge et Blanc']::text[], 5, 'France'),
  ('Olympique Lyonnais', 'Lyon', ARRAY['OL', 'Olympique Lyon', 'Les Gones', 'Les Lyonnais']::text[], 5, 'France'),
  ('OGC Nice', 'Nice', ARRAY['Olympique Gymnaste Club Nice', 'Les Aiglons', 'Le Gym']::text[], 5, 'France'),
  ('Lille OSC', 'Lille', ARRAY['LOSC', 'LOSC Lille', 'Lille Olympique Sporting Club', 'Les Dogues']::text[], 5, 'France'),
  ('RC Lens', 'Lens', ARRAY['Racing Club de Lens', 'Sang et Or']::text[], 5, 'France'),
  ('Stade Rennais', 'Rennes', ARRAY['Stade Rennais FC', 'SRFC', 'Rouge et Noir']::text[], 5, 'France'),
  ('Stade Brestois', 'Brest', ARRAY['Stade Brestois 29', 'SB29', 'Les Ti-Zefs', 'Pirates']::text[], 5, 'France'),
  ('Toulouse FC', 'Toulouse', ARRAY['TFC', 'Les Violets', 'Le Téfécé']::text[], 5, 'France'),
  ('RC Strasbourg', 'Strasbourg', ARRAY['RC Strasbourg Alsace', 'Racing', 'Le Racing']::text[], 5, 'France'),
  ('FC Nantes', 'Nantes', ARRAY['Football Club de Nantes', 'Les Canaris', 'Les Jaunes et Verts']::text[], 5, 'France'),
  ('Le Havre AC', 'Le Havre', ARRAY['Le Havre Athletic Club', 'HAC', 'Les Ciel et Marine']::text[], 5, 'France'),
  ('Angers SCO', 'Angers', ARRAY['SCO Angers', 'Sporting Club de l''Ouest', 'Les Scoïstes']::text[], 5, 'France'),
  ('AJ Auxerre', 'Auxerre', ARRAY['Association de la Jeunesse Auxerroise', 'AJA', 'Les Bourguignons']::text[], 5, 'France'),
  ('FC Metz', 'Metz', ARRAY['Football Club de Metz', 'Les Grenats']::text[], 5, 'France'),
  ('FC Lorient', 'Lorient', ARRAY['Football Club Lorient-Bretagne Sud', 'Les Merlus']::text[], 5, 'France'),
  ('Paris FC', 'Paris FC', ARRAY['PFC', 'Football Club de Paris']::text[], 5, 'France')
ON CONFLICT (name, league_id) DO NOTHING;;